Версия-Doika-в-footer
diglabby/doika pull request #737
Opened 2020-05-25 12:09 UTC by andrei-roh

Добавлено отображение версии Doika в footer как решение проблемы https://github.com/diglabby/doika/issues/196

2020-05-25 12:12 UTC, andrei-roh commented
> Дзякуй за стварэнне твайго першага Pull Request для Doika 👍! Калі ласка азнаемся з [правіламі афармлення PR](/diglabby/doika/CONTRIBUTING.md).

Кстати битая ссылка

2020-05-25 13:08 UTC, rizomaa commented
@lptn падкажы калі ласка дзе усё гэта заточваецца?
"
Дзякуй за стварэнне твайго першага Pull Request для Doika +1! Калі ласка азнаемся з правіламі афармлення PR.
"

2020-05-26 06:07 UTC, lptn commented
.github дырыкторыя ў рэпазіторыі, файл завецца welcome ці нешта падобнае

On Mon, May 25, 2020, 16:08 Mister Cable <notifications@github.com> wrote:

> @lptn <https://github.com/lptn> падкажы калі ласка дзе усё гэта
> заточваецца?
> "
> Дзякуй за стварэнне твайго першага Pull Request для Doika +1! Калі ласка
> азнаемся з правіламі афармлення PR.
> "
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/diglabby/doika/pull/737#issuecomment-633564099>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABIITX7LNJABNBDT7SOVEQLRTJUU7ANCNFSM4NJPE2TA>
> .
>

2020-05-26 09:08 UTC, alies-dev submitted a review, later dismissed
@andrei-roh

Дзякуй! Амаль усе добра!

Некаторыя заўвагі:
 - ня варта змяняць код-стайлінг усяго файла - гэта толькі распачынае кодстайл вайнушкі і стварае шмат шуму ў праглядзе зменаў на GH
 - як думаеш, ці есьць нейкі сэнс рэнрэр footer  аддаць у Vue, мы ж нічога не збіраемся мяняць у ім, ен не мусіць быць інтэрактыўным; Варыянт - перанесці яго ў layout які генеруецца Laravel
 - ці ёсць нейкі сэнс window.settings заюіраць у Vue а не выкарыстоўваць наўпросткі? Ці мы будзем версію таксама транслейціць і яно нам трэба?
 - ці варта перадаваць увесь window.settings калі нам толькі трэба адно значэнне з гэтага масіву?
 - ці ня варта перанесці window.settings у асобны ES модуль і імпарціць яго ў розных vue кампанентах?

Некаторыя мае прапановы/пытанні канфліктуюць паміж собку, я ведаю :)

2020-05-26 11:47 UTC, andrei-roh commented
@lptn Спасибо за анализ. По замечаниям, если я правильно понял смысл замечаний:
- это получилось вследствие недостатка опыта: я не нашел оптимального места для appVersion;
- я так понимаю это может увеличить быстродействие? "Ничего не собираемся менять" это сегодня, а завтра добавим ссылку на условия использования модуля, а потом значки соцсетей,  рекламу или портреты команды разработчиков, а может список спонсоров;
- у меня не получилось просто потребовать windows.setting без Vue. Перевод нужен, как раз в файлах с переводами не задействовано 'version';
- полностью согласен, не нужно передавать весь window.settings, достаточно сразу ввести  appVersion с default: window.settings.appVersion. Я переделаю этот момент;
- если от window.settings кроме версии в footer нам больше ничего не нужно, то зачем отдельный модуль.

2020-05-26 14:28 UTC, lptn commented
>я так понимаю это может увеличить быстродействие? "Ничего не собираемся менять" это сегодня, а завтра добавим ссылку на условия использования модуля, а потом значки соцсетей, рекламу или портреты команды разработчиков, а может список спонсоров;

я маю на ўвазе што не збіраемся мяняць ДЫНАМІЧНА. Можна мінімізаваць частку старонкі якая генеруецца Vue і той жа футэр генерыць на сэрверы сродкамі Laravel і аддаваць разам з layout (макетам старонкі). Але гэта ідэя не для гэтага PR, выходзіць за межы яго. Vue ды іншыя фроймворкі і лібы кшталту React трэба толькі для дынамічнага кантэнту, а футэр у нас - статыка.

>у меня не получилось просто потребовать windows.setting без Vue. Перевод нужен, как раз в файлах с переводами не задействовано 'version';

Можам проста Doika v2.X пісаць не перакладу, ды і пераклад можа здязйсняцца сродкамі Laravel, але гэта як і папярэдні пункт -- ідэя для аптымізаціі

>полностью согласен, не нужно передавать весь window.settings, достаточно сразу ввести appVersion с default: window.settings.appVersion. Я переделаю этот момент;

Клас, дзякуй! А можаш перадаваць нумар версіі праз пропсы а то зараз калі я правільна разумею мы паказваем толькі дэфолт які бярэцца з глабальнага window, што не класна для будучыні праекта і тэставання кампанента (няяўная залежнасць)

>если от window.settings кроме версии в footer нам больше ничего не нужно, то зачем отдельный модуль.

глабальны стэйт == дрэнна; Але ў ідыяле проста дэфолт выпіліць з гэтага модуля і перадаваць пропсам -- там вы прыбярэм гэтую залежнасць

2020-05-26 14:29 UTC, alies-dev requested changes
@andrei-roh 
Дзякуй за аператыўнасць!

>я так понимаю это может увеличить быстродействие? "Ничего не собираемся менять" это сегодня, а завтра добавим ссылку на условия использования модуля, а потом значки соцсетей, рекламу или портреты команды разработчиков, а может список спонсоров;

я маю на ўвазе што не збіраемся мяняць ДЫНАМІЧНА. Можна мінімізаваць частку старонкі якая генеруецца Vue і той жа футэр генерыць на сэрверы сродкамі Laravel і аддаваць разам з layout (макетам старонкі). Але гэта ідэя не для гэтага PR, выходзіць за межы яго. Vue ды іншыя фроймворкі і лібы кшталту React трэба толькі для дынамічнага кантэнту, а футэр у нас - статыка.

>у меня не получилось просто потребовать windows.setting без Vue. Перевод нужен, как раз в файлах с переводами не задействовано 'version';

Можам проста Doika v2.X пісаць не перакладу, ды і пераклад можа здязйсняцца сродкамі Laravel, але гэта як і папярэдні пункт -- ідэя для аптымізаціі

>полностью согласен, не нужно передавать весь window.settings, достаточно сразу ввести appVersion с default: window.settings.appVersion. Я переделаю этот момент;

Клас, дзякуй! А можаш перадаваць нумар версіі праз пропсы а то зараз калі я правільна разумею мы паказваем толькі дэфолт які бярэцца з глабальнага window, што не класна для будучыні праекта і тэставання кампанента (няяўная залежнасць)

>если от window.settings кроме версии в footer нам больше ничего не нужно, то зачем отдельный модуль.

глабальны стэйт == дрэнна; Але ў ідыяле проста дэфолт выпіліць з гэтага модуля і перадаваць пропсам -- там вы прыбярэм гэтую залежнасць

____________
Такім чынам: пракітываем версію пропсам і выпіліваем default і любыя выкарыстоўванні window у кампаненце

2020-05-26 18:13 UTC, andrei-roh commented
@lptn 

> я маю на ўвазе што не збіраемся мяняць ДЫНАМІЧНА. Можна мінімізаваць частку старонкі якая генеруецца Vue і той жа футэр генерыць на сэрверы сродкамі Laravel і аддаваць разам з layout (макетам старонкі). Але гэта ідэя не для гэтага PR, выходзіць за межы яго. Vue ды іншыя фроймворкі і лібы кшталту React трэба толькі для дынамічнага кантэнту, а футэр у нас - статыка.

Я примерно понял мысль насчет динамики

> Можам проста Doika v2.X пісаць не перакладу, ды і пераклад можа здязйсняцца сродкамі Laravel, але гэта як і папярэдні пункт -- ідэя для аптымізаціі

Хорошая альтернатива переводу, поменяю на v2.X

> Такім чынам: пракітываем версію пропсам і выпіліваем default і любыя выкарыстоўванні window у кампаненце

Понял, но не все. Я убрал window из компонента, а вот как убрать default не понял - мои попытки не получились, если возможно, прошу помощи

2020-05-26 20:51 UTC, lptn commented
@andrei-roh 
Зразумеў

Я меў на ўвазе пракінуць версію дойкі ў кампанент Footer праз пропсы так жа як мы гэта рабім з іншымі пропсамі вось тут https://github.com/diglabby/doika/blob/79b0ff29db52c03bd7ffec27a6aacd8708eb4187/resources/js/dashboard/containers/Full.vue#L27-L29

Пасля такой аперацыі нам дэфолт не патрэбны, пампанент мусіць ня ведаць пра аб'ект window

2020-05-27 15:48 UTC, andrei-roh commented
@lptn Добрый вечер! Спасибо за подсказку, я подправил Footer.vue и изменил Full.vue.

2020-05-28 20:09 UTC, merged

2020-05-28 22:15 UTC, lptn commented on resources/js/dashboard/components/Footer.vue
> +      default: ''
@andrei-roh

Дзякуй за працу, бачу ПР ужо ўмёржылі, але хачу падзяліцца яшчэ адной ідэяй

default не абавязковы, нават лішні, бо првучае да дрэнных звычак і вядзе да дрэннага праектавання кампанентаў;



Большая частка дадзеных мусіцб быць абавязковая, а значыць без default:
```js
appVersion: {
    type: String,
    required: true,
},
```

2020-05-29 06:59 UTC, andrei-roh commented on resources/js/dashboard/components/Footer.vue
> +      default: ''
@lptn Понял, спасибо за подробное объяснение

2020-05-29 13:59 UTC, lptn commented on resources/js/dashboard/components/Footer.vue
> +      default: ''
@andrei-roh

зрабі калі ласка яшчэ адзін ПР дзе зробім прапанаваныя мною змены. Дзякуй!

2020-05-29 17:27 UTC, andrei-roh commented on resources/js/dashboard/components/Footer.vue
> +      default: ''
@lptn https://github.com/diglabby/doika/pull/746