Refactor code for check payment status feature
diglabby/doika pull request #751
Opened 2020-06-03 10:57 UTC by Tyuba4

1. Отрефакторил код в соответствии с замечаниями @lptn.
2. Ишью: #732
3. Для тестирования можно отправить POST запрос на /doika/widget/api/check-payment-status с параметром token в который необходимо записать токен платежа. В ответе придет JSON c ответом bepaid и отдельной строкой текущий статус платежа. Пока платеж не произошел или не был откланонен статус будет "error".

2020-06-03 11:08 UTC, alies-dev requested changes
Дзякуй, так значна лепей! Але давай яшчэ палепшым.

Я па-ранейшаму ня ўпэўнены што там гэты функцыянал патрэбны, пагэтаму надта глыбока ў разгляд гэтага ПР не ўлазіў, спадзяюся хутка выпілім гэты код :)

2020-06-03 11:08 UTC, alies-dev commented on app/Http/Controllers/Widget/CheckPaymentStatusController.php
> +        if ($request->has('token')) {
```php
$this->validate($request, ['token' => ['required']])
```

2020-06-03 11:08 UTC, lptn commented on app/Http/Controllers/Widget/CheckPaymentStatusController.php
> +        echo $arrResponse['status'];
экшэны кантроллераў мусяць вяртаць дадзеныя а не пісаць наўпросткі ў output

можна вось так:
```php
$output = $arrResponse['json_response'];
$output .= '<br>// Status line: <br>';
$output .= $arrResponse['status']

return response($output);
```

2020-06-03 11:08 UTC, lptn commented on app/Services/PaymentGateways/BePaidPaymentGateway.php
> +    public function checkPaymentStatus($token)
дадай кали ласка тайп хинты (пры гэтым `@param string $token` + `@return array` з PHPDoc робяцца непатрэбнымі)
```php
public function checkPaymentStatus(string $token): array
 ```

2020-06-03 11:08 UTC, lptn commented on app/Services/PaymentGateways/BePaidPaymentGateway.php
> +        $arrResponse['json_response'] = $response;
`json_response`  - неадназначнае імя. Калі я бачу json -  я звычайна чакаю тып string, а тут будзе ці array ці stdClass instance. Можна проста пераназваць "gateway_response" і будзе лепей, па-ранейшаму невядома што там, але хаця б не будзе ствараць няправільных чаканьняў

2020-06-03 11:12 UTC, lptn commented on app/Http/Controllers/Widget/CheckPaymentStatusController.php
> +    public function checkPaymentStatus(BePaidPaymentGateway $gateway, Request $request)
гэты кантроллер мяркуе што у нас толькі BePaid есьць з PaymentGateway , так? З іншымі ен не працуе, але гэта не ясна ў URL ці параметраў action

Ёсць сэнс рабіць абстракцыю толькі калі мы будзем упэўнены што гэты функцыянал нам патрэюны на некалькіх PaymentGateways, пакуль жа давай кантроллер і роўт перейменуем так каб было ясна што гэта працуе толькі з BePaid

2020-06-08 21:12 UTC, Tyuba4 commented on app/Http/Controllers/Widget/CheckPaymentStatusController.php
> +        if ($request->has('token')) {
"Я па-ранейшаму ня ўпэўнены што там гэты функцыянал патрэбны"
Ok, может тогда лучше делать проверку статуса платежа в БД, на предмет того, отработали ли вебхуки?

2020-06-09 21:49 UTC, lptn commented on app/Http/Controllers/Widget/CheckPaymentStatusController.php
> +        if ($request->has('token')) {
прапаную слухаць вэбхукі і выкарыстоўваць long polling для радэрэкта (апрацоўшчык вэбхука запісвае інфу ў БД а рэдзірэкт заканчваецца толькі тады калі інфа ў БД ёсьць (while do цякл ці што небудзь падобнае))

2020-06-11 14:17 UTC, rizomaa commented on app/Http/Controllers/Widget/CheckPaymentStatusController.php
> +    public function checkPaymentStatus(BePaidPaymentGateway $gateway, Request $request)
@lptn а чаму зараз нельга закласци маштабуемасць на іншыя gateways?

2020-06-11 16:15 UTC, lptn commented on app/Http/Controllers/Widget/CheckPaymentStatusController.php
> +    public function checkPaymentStatus(BePaidPaymentGateway $gateway, Request $request)
@rizomaa 
я такога не казаў. Можна. :) Але ў гэтым ПР гэта не зроблена, мая заўага была пра тое што гэта не зроблена

2020-06-11 16:36 UTC, rizomaa commented on app/Http/Controllers/Widget/CheckPaymentStatusController.php
> +    public function checkPaymentStatus(BePaidPaymentGateway $gateway, Request $request)
@lptn дзякуй=)насамрэч варта мыслиць маштабуемасцю па плацёжным шлузам, мы у тым ліку з-за яе задумалі версію 2.0 і яна будзе=)

2020-07-06 16:09 UTC, merged

2020-07-08 07:29 UTC, Tyuba4 commented
> @Tyuba4
> яшчэ і URL трэба падправіць

Ok, подправим следующим коммитом